"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

export type Language = "en" | "ta" | "hi" | "ml" | "te" | "bn" | "mr" | "gu" | "ur" | "pa" | "ks" | "as" | "mni" | "or" | "kok"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome: "Welcome to FinAI",
    welcomeSubtitle: "Your AI-powered financial assistant",
    checkLoanRisk: "Check Loan Risk",
    bankRates: "Bank Rates",
    goldLoan: "Gold Loan",
    talkToAI: "Talk to AI Assistant",
    uploadDocuments: "Upload Documents",
    financialHealth: "Financial Health Score",
    loanRiskForm: "Loan Risk Assessment",
    income: "Monthly Income",
    expenses: "Monthly Expenses",
    existingLoans: "Existing Loans",
    emi: "Current EMI",
    calculateRisk: "Calculate Risk",
    riskScore: "Risk Score",
    lowRisk: "Low Risk",
    mediumRisk: "Medium Risk",
    highRisk: "High Risk",
    aiChat: "AI Financial Assistant",
    typeMessage: "Type your message...",
    send: "Send",
    analyzing: "Analyzing...",
    extractingData: "Extracting data...",
    financialRoadmap: "Financial Roadmap",
    repaymentPlan: "Repayment Plan",
    tips: "Financial Tips",
    creditSimulator: "Credit Simulator",
    documentUpload: "Document Upload",
    uploadPDF: "Upload PDF or Image",
    extractedData: "Extracted Data",
    useForPrediction: "Use this data for risk prediction",
    reminders: "Reminders",
    setReminder: "Set Reminder",
    whatsappReminder: "WhatsApp Reminder",
    confirmReminder: "Reminder Set Successfully",
    demoMode: "Demo Mode",
    selectLanguage: "Select Language",
    dashboard: "Dashboard",
    simulator: "Simulator",
    roadmap: "Roadmap",
    chat: "Chat",
    documents: "Documents",
    settings: "Settings",
    // Form fields
    loanAmount: "Loan Amount",
    tenure: "Tenure (Months)",
    loanPurpose: "Loan Purpose",
    cibilScore: "CIBIL Score",
    age: "Age (Years)",
    employmentType: "Employment Type",
    stabilityYears: "Years in Current Job",
    sectionLoanDetails: "Loan You Want to Take",
    sectionCreditProfile: "Your Credit Profile",
    // Bank rates
    bankRateComparison: "Bank Rate Comparison",
    yourLoanProfile: "Your Loan Profile",
    compareRates: "Compare Rates",
    eligible: "Eligible",
    notEligible: "Not Eligible",
    bestPick: "Best Pick for You",
    contactBankBtn: "Contact Bank",
    sendInquiry: "Send Inquiry",
    processingFee: "Processing Fee",
    // Gold loan
    goldWeight: "Gold Weight (grams)",
    goldPurity: "Gold Purity (Karats)",
    eligibleLoanAmt: "Eligible Loan Amount",
    calculateLoan: "Calculate",
    viewGoldLoanBanks: "View Gold Loan Banks",
    // Dashboard
    checkMyEligibility: "Check My Eligibility",
    compareBanks: "Compare Banks",
    yourLoanJourney: "Your Loan Journey",
    allFeatures: "All Features",
    // Roadmap & common
    generatePlan: "Generate Repayment Plan",
    monthlyEmi: "Monthly EMI",
    totalInterest: "Total Interest",
    totalPayable: "Total Payable",
    govtSchemes: "Govt Schemes",
    negotiate: "Negotiate Rate",
  },
  ta: {
    welcome: "FinAI-க்கு வரவேற்கிறோம்",
    welcomeSubtitle: "உங்கள் AI நிதி உதவியாளர்",
    checkLoanRisk: "கடன் ஆபத்தை சரிபார்க்கவும்",
    talkToAI: "AI உதவியாளருடன் பேசுங்கள்",
    uploadDocuments: "ஆவணங்களை பதிவேற்றவும்",
    financialHealth: "நிதி ஆரோக்கிய மதிப்பெண்",
    loanRiskForm: "கடன் ஆபத்து மதிப்பீடு",
    income: "மாத வருமானம்",
    expenses: "மாத செலவுகள்",
    existingLoans: "தற்போதைய கடன்கள்",
    emi: "தற்போதைய EMI",
    calculateRisk: "ஆபத்தை கணக்கிடுங்கள்",
    riskScore: "ஆபத்து மதிப்பெண்",
    lowRisk: "குறைந்த ஆபத்து",
    mediumRisk: "நடுத்தர ஆபத்து",
    highRisk: "அதிக ஆபத்து",
    aiChat: "AI நிதி உதவியாளர்",
    typeMessage: "உங்கள் செய்தியை உள்ளிடுங்கள்...",
    send: "அனுப்பு",
    analyzing: "பகுப்பாய்வு செய்கிறது...",
    extractingData: "தரவை எடுக்கிறது...",
    financialRoadmap: "நிதி வழிகாட்டி",
    repaymentPlan: "திருப்பிச் செலுத்தும் திட்டம்",
    tips: "நிதி குறிப்புகள்",
    creditSimulator: "கடன் உருவகப்படுத்தி",
    documentUpload: "ஆவண பதிவேற்றம்",
    uploadPDF: "PDF அல்லது படத்தை பதிவேற்றவும்",
    extractedData: "எடுக்கப்பட்ட தரவு",
    useForPrediction: "ஆபத்து கணிப்புக்கு இந்த தரவைப் பயன்படுத்துங்கள்",
    reminders: "நினைவூட்டல்கள்",
    setReminder: "நினைவூட்டல் அமைக்கவும்",
    whatsappReminder: "WhatsApp நினைவூட்டல்",
    confirmReminder: "நினைவூட்டல் வெற்றிகரமாக அமைக்கப்பட்டது",
    demoMode: "செயல்விளக்க முறை",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    dashboard: "டாஷ்போர்டு",
    simulator: "உருவகப்படுத்தி",
    roadmap: "வழிகாட்டி",
    chat: "அரட்டை",
    documents: "ஆவணங்கள்",
    settings: "அமைப்புகள்",
    loanAmount: "கடன் தொகை",
    tenure: "காலம் (மாதங்கள்)",
    loanPurpose: "கடன் நோக்கம்",
    cibilScore: "CIBIL மதிப்பெண்",
    age: "வயது (ஆண்டுகள்)",
    employmentType: "வேலை வகை",
    stabilityYears: "தற்போதைய வேலையில் ஆண்டுகள்",
    sectionLoanDetails: "நீங்கள் எடுக்க விரும்பும் கடன்",
    sectionCreditProfile: "உங்கள் கடன் சுயவிவரம்",
    bankRateComparison: "வங்கி வட்டி ஒப்பீடு",
    yourLoanProfile: "உங்கள் கடன் விவரங்கள்",
    compareRates: "வட்டி ஒப்பிடுங்கள்",
    eligible: "தகுதியான",
    notEligible: "தகுதியற்ற",
    bestPick: "சிறந்த தேர்வு",
    contactBankBtn: "வங்கியை தொடர்பு கொள்ளுங்கள்",
    sendInquiry: "விசாரணை அனுப்புங்கள்",
    processingFee: "செயலாக்க கட்டணம்",
    goldWeight: "தங்க எடை (கிராம்)",
    goldPurity: "தங்க தூய்மை (கேரட்)",
    eligibleLoanAmt: "தகுதியான கடன் தொகை",
    calculateLoan: "கணக்கிடுங்கள்",
    viewGoldLoanBanks: "தங்கக் கடன் வங்கிகள்",
    checkMyEligibility: "எனது தகுதியை சரிபார்க்கவும்",
    compareBanks: "வங்கிகளை ஒப்பிடுங்கள்",
    yourLoanJourney: "உங்கள் கடன் பயணம்",
    allFeatures: "அனைத்து வசதிகள்",
    generatePlan: "திருப்பிச் செலுத்தும் திட்டம் உருவாக்கு",
    monthlyEmi: "மாத EMI",
    totalInterest: "மொத்த வட்டி",
    totalPayable: "மொத்த செலுத்தவேண்டியது",
    govtSchemes: "அரசு திட்டங்கள்",
    negotiate: "வட்டி பேச்சுவார்த்தை",
  },
  hi: {
    welcome: "FinAI में आपका स्वागत है",
    welcomeSubtitle: "आपका AI वित्तीय सहायक",
    checkLoanRisk: "ऋण जोखिम जांचें",
    talkToAI: "AI सहायक से बात करें",
    uploadDocuments: "दस्तावेज़ अपलोड करें",
    financialHealth: "वित्तीय स्वास्थ्य स्कोर",
    loanRiskForm: "ऋण जोखिम मूल्यांकन",
    income: "मासिक आय",
    expenses: "मासिक खर्च",
    existingLoans: "मौजूदा ऋण",
    emi: "वर्तमान EMI",
    calculateRisk: "जोखिम की गणना करें",
    riskScore: "जोखिम स्कोर",
    lowRisk: "कम जोखिम",
    mediumRisk: "मध्यम जोखिम",
    highRisk: "उच्च जोखिम",
    aiChat: "AI वित्तीय सहायक",
    typeMessage: "अपना संदेश लिखें...",
    send: "भेजें",
    analyzing: "विश्लेषण हो रहा है...",
    extractingData: "डेटा निकाला जा रहा है...",
    financialRoadmap: "वित्तीय रोडमैप",
    repaymentPlan: "पुनर्भुगतान योजना",
    tips: "वित्तीय सुझाव",
    creditSimulator: "क्रेडिट सिम्युलेटर",
    documentUpload: "दस्तावेज़ अपलोड",
    uploadPDF: "PDF या छवि अपलोड करें",
    extractedData: "निकाला गया डेटा",
    useForPrediction: "जोखिम भविष्यवाणी के लिए इस डेटा का उपयोग करें",
    reminders: "अनुस्मारक",
    setReminder: "अनुस्मारक सेट करें",
    whatsappReminder: "WhatsApp अनुस्मारक",
    confirmReminder: "अनुस्मारक सफलतापूर्वक सेट किया गया",
    demoMode: "डेमो मोड",
    selectLanguage: "भाषा चुनें",
    dashboard: "डैशबोर्ड",
    simulator: "सिम्युलेटर",
    roadmap: "रोडमैप",
    chat: "चैट",
    documents: "दस्तावेज़",
    settings: "सेटिंग्स",
    loanAmount: "ऋण राशि",
    tenure: "अवधि (महीने)",
    loanPurpose: "ऋण का उद्देश्य",
    cibilScore: "CIBIL स्कोर",
    age: "आयु (वर्ष)",
    employmentType: "रोज़गार का प्रकार",
    stabilityYears: "वर्तमान नौकरी में वर्ष",
    sectionLoanDetails: "आप जो ऋण लेना चाहते हैं",
    sectionCreditProfile: "आपकी क्रेडिट प्रोफ़ाइल",
    bankRateComparison: "बैंक दर तुलना",
    yourLoanProfile: "आपका ऋण प्रोफ़ाइल",
    compareRates: "दरें तुलना करें",
    eligible: "पात्र",
    notEligible: "अपात्र",
    bestPick: "आपके लिए सर्वश्रेष्ठ",
    contactBankBtn: "बैंक से संपर्क करें",
    sendInquiry: "पूछताछ भेजें",
    processingFee: "प्रसंस्करण शुल्क",
    goldWeight: "सोने का वजन (ग्राम)",
    goldPurity: "सोने की शुद्धता (कैरेट)",
    eligibleLoanAmt: "पात्र ऋण राशि",
    calculateLoan: "गणना करें",
    viewGoldLoanBanks: "गोल्ड लोन बैंक देखें",
    checkMyEligibility: "मेरी पात्रता जांचें",
    compareBanks: "बैंकों की तुलना करें",
    yourLoanJourney: "आपकी ऋण यात्रा",
    allFeatures: "सभी सुविधाएं",
    generatePlan: "पुनर्भुगतान योजना बनाएं",
    monthlyEmi: "मासिक EMI",
    totalInterest: "कुल ब्याज",
    totalPayable: "कुल देय",
    govtSchemes: "सरकारी योजनाएं",
    negotiate: "ब्याज दर बातचीत",
  },
  ml: {
    welcome: "FinAI-ലേക്ക് സ്വാഗതം",
    welcomeSubtitle: "നിങ്ങളുടെ AI സാമ്പത്തിക സഹായി",
    checkLoanRisk: "വായ്പാ അപകടസാധ്യത പരിശോധിക്കുക",
    talkToAI: "AI സഹായിയോട് സംസാരിക്കുക",
    uploadDocuments: "രേഖകൾ അപ്‌ലോഡ് ചെയ്യുക",
    financialHealth: "സാമ്പത്തിക ആരോഗ്യ സ്കോർ",
    loanRiskForm: "വായ്പാ അപകടസാധ്യത വിലയിരുത്തൽ",
    income: "പ്രതിമാസ വരുമാനം",
    expenses: "പ്രതിമാസ ചെലവുകൾ",
    existingLoans: "നിലവിലുള്ള വായ്പകൾ",
    emi: "നിലവിലെ EMI",
    calculateRisk: "അപകടസാധ്യത കണക്കാക്കുക",
    riskScore: "അപകടസാധ്യത സ്കോർ",
    lowRisk: "കുറഞ്ഞ അപകടസാധ്യത",
    mediumRisk: "ഇടത്തരം അപകടസാധ്യത",
    highRisk: "ഉയർന്ന അപകടസാധ്യത",
    aiChat: "AI സാമ്പത്തിക സഹായി",
    typeMessage: "നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക...",
    send: "അയയ്ക്കുക",
    analyzing: "വിശകലനം ചെയ്യുന്നു...",
    extractingData: "ഡാറ്റ എക്‌സ്‌ട്രാക്റ്റ് ചെയ്യുന്നു...",
    financialRoadmap: "സാമ്പത്തിക റോഡ്‌മാപ്പ്",
    repaymentPlan: "തിരിച്ചടവ് പ്ലാൻ",
    tips: "സാമ്പത്തിക ടിപ്പുകൾ",
    creditSimulator: "ക്രെഡിറ്റ് സിമുലേറ്റർ",
    documentUpload: "രേഖ അപ്‌ലോഡ്",
    uploadPDF: "PDF അല്ലെങ്കിൽ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    extractedData: "എക്‌സ്‌ട്രാക്റ്റ് ചെയ്ത ഡാറ്റ",
    useForPrediction: "അപകടസാധ്യത പ്രവചനത്തിന് ഈ ഡാറ്റ ഉപയോഗിക്കുക",
    reminders: "ഓർമ്മപ്പെടുത്തലുകൾ",
    setReminder: "ഓർമ്മപ്പെടുത്തൽ സജ്ജമാക്കുക",
    whatsappReminder: "WhatsApp ഓർമ്മപ്പെടുത്തൽ",
    confirmReminder: "ഓർമ്മപ്പെടുത്തൽ വിജയകരമായി സജ്ജമാക്കി",
    demoMode: "ഡെമോ മോഡ്",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    dashboard: "ഡാഷ്ബോർഡ്",
    simulator: "സിമുലേറ്റർ",
    roadmap: "റോഡ്‌മാപ്പ്",
    chat: "ചാറ്റ്",
    documents: "രേഖകൾ",
    settings: "ക്രമീകരണങ്ങൾ",
    loanAmount: "വായ്പ തുക",
    tenure: "കാലാവധി (മാസം)",
    loanPurpose: "വായ്പ ഉദ്ദേശ്യം",
    cibilScore: "CIBIL സ്കോർ",
    age: "പ്രായം (വർഷം)",
    employmentType: "തൊഴിൽ തരം",
    stabilityYears: "നിലവിലെ ജോലിയിൽ വർഷങ്ങൾ",
    sectionLoanDetails: "നിങ്ങൾ എടുക്കാൻ ആഗ്രഹിക്കുന്ന വായ്പ",
    sectionCreditProfile: "നിങ്ങളുടെ ക്രെഡിറ്റ് പ്രൊഫൈൽ",
    bankRateComparison: "ബാങ്ക് പലിശ താരതമ്യം",
    yourLoanProfile: "നിങ്ങളുടെ വായ്പ വിവരങ്ങൾ",
    compareRates: "പലിശ നിരക്ക് താരതമ്യം",
    eligible: "യോഗ്യൻ",
    notEligible: "അയോഗ്യൻ",
    bestPick: "നിങ്ങൾക്ക് ഏറ്റവും അനുയോജ്യം",
    contactBankBtn: "ബാങ്കിൽ ബന്ധപ്പെടുക",
    sendInquiry: "അന്വേഷണം അയയ്ക്കുക",
    processingFee: "പ്രോസസ്സിംഗ് ഫീ",
    goldWeight: "സ്വർണ്ണ ഭാരം (ഗ്രാം)",
    goldPurity: "സ്വർണ്ണ ശുദ്ധി (കാരറ്റ്)",
    eligibleLoanAmt: "യോഗ്യമായ വായ്പ തുക",
    calculateLoan: "കണക്കാക്കുക",
    viewGoldLoanBanks: "ഗോൾഡ് ലോൺ ബാങ്കുകൾ കാണുക",
    checkMyEligibility: "എന്റെ യോഗ്യത പരിശോധിക്കുക",
    compareBanks: "ബാങ്കുകൾ താരതമ്യം ചെയ്യുക",
    yourLoanJourney: "നിങ്ങളുടെ വായ്പ യാത്ര",
    allFeatures: "എല്ലാ സവിശേഷതകളും",
    generatePlan: "തിരിച്ചടവ് പ്ലാൻ ഉണ്ടാക്കുക",
    monthlyEmi: "പ്രതിമാസ EMI",
    totalInterest: "മൊത്തം പലിശ",
    totalPayable: "മൊത്തം അടയ്ക്കേണ്ടത്",
    govtSchemes: "സർക്കാർ പദ്ധതികൾ",
    negotiate: "പലിശ ചർച്ച",
  },
  te: {
    welcome: "FinAI కి స్వాగతం",
    welcomeSubtitle: "మీ AI ఆర్థిక సహాయకుడు",
    checkLoanRisk: "రుణ ప్రమాదాన్ని తనిఖీ చేయండి",
    talkToAI: "AI సహాయకునితో మాట్లాడండి",
    uploadDocuments: "డాక్యుమెంట్లను అప్‌లోడ్ చేయండి",
    financialHealth: "ఆర్థిక ఆరోగ్య స్కోర్",
    loanRiskForm: "రుణ ప్రమాద అంచనా",
    income: "నెలవారీ ఆదాయం",
    expenses: "నెలవారీ ఖర్చులు",
    existingLoans: "ఇప్పటికే ఉన్న రుణాలు",
    emi: "ప్రస్తుత EMI",
    calculateRisk: "ప్రమాదాన్ని లెక్కించండి",
    riskScore: "ప్రమాద స్కోర్",
    lowRisk: "తక్కువ ప్రమాదం",
    mediumRisk: "మధ్యస్థ ప్రమాదం",
    highRisk: "అధిక ప్రమాదం",
    aiChat: "AI ఆర్థిక సహాయకుడు",
    typeMessage: "మీ సందేశాన్ని టైప్ చేయండి...",
    send: "పంపు",
    analyzing: "విశ్లేషిస్తోంది...",
    extractingData: "డేటాను సంగ్రహిస్తోంది...",
    financialRoadmap: "ఆర్థిక రోడ్‌మ్యాప్",
    repaymentPlan: "తిరిగి చెల్లింపు ప్రణాళిక",
    tips: "ఆర్థిక చిట్కాలు",
    creditSimulator: "క్రెడిట్ సిమ్యులేటర్",
    documentUpload: "డాక్యుమెంట్ అప్‌లోడ్",
    uploadPDF: "PDF లేదా చిత్రాన్ని అప్‌లోడ్ చేయండి",
    extractedData: "సంగ్రహించిన డేటా",
    useForPrediction: "ప్రమాద అంచనా కోసం ఈ డేటాను ఉపయోగించండి",
    reminders: "రిమైండర్లు",
    setReminder: "రిమైండర్ సెట్ చేయండి",
    whatsappReminder: "WhatsApp రిమైండర్",
    confirmReminder: "రిమైండర్ విజయవంతంగా సెట్ చేయబడింది",
    demoMode: "డెమో మోడ్",
    selectLanguage: "భాషను ఎంచుకోండి",
    dashboard: "డ్యాష్‌బోర్డ్",
    simulator: "సిమ్యులేటర్",
    roadmap: "రోడ్‌మ్యాప్",
    chat: "చాట్",
    documents: "డాక్యుమెంట్లు",
    settings: "సెట్టింగ్‌లు",
    loanAmount: "రుణ మొత్తం",
    tenure: "వ్యవధి (నెలలు)",
    loanPurpose: "రుణ ప్రయోజనం",
    cibilScore: "CIBIL స్కోర్",
    age: "వయసు (సంవత్సరాలు)",
    employmentType: "ఉద్యోగ రకం",
    stabilityYears: "ప్రస్తుత ఉద్యోగంలో సంవత్సరాలు",
    sectionLoanDetails: "మీరు తీసుకోవాలనుకుంటున్న రుణం",
    sectionCreditProfile: "మీ క్రెడిట్ ప్రొఫైల్",
    bankRateComparison: "బ్యాంక్ రేటు పోలిక",
    yourLoanProfile: "మీ రుణ వివరాలు",
    compareRates: "రేట్లు పోల్చండి",
    eligible: "అర్హులు",
    notEligible: "అర్హత లేనివారు",
    bestPick: "మీకు అత్యుత్తమం",
    contactBankBtn: "బ్యాంక్‌ను సంప్రదించండి",
    sendInquiry: "విచారణ పంపండి",
    processingFee: "ప్రాసెసింగ్ ఫీజు",
    goldWeight: "బంగారు బరువు (గ్రాములు)",
    goldPurity: "బంగారు స్వచ్ఛత (క్యారెట్లు)",
    eligibleLoanAmt: "అర్హమైన రుణ మొత్తం",
    calculateLoan: "లెక్కించండి",
    viewGoldLoanBanks: "గోల్డ్ లోన్ బ్యాంకులు చూడండి",
    checkMyEligibility: "నా అర్హతను తనిఖీ చేయండి",
    compareBanks: "బ్యాంకులను పోల్చండి",
    yourLoanJourney: "మీ రుణ ప్రయాణం",
    allFeatures: "అన్ని సౌకర్యాలు",
    generatePlan: "తిరిగి చెల్లింపు ప్రణాళిక రూపొందించు",
    monthlyEmi: "నెలవారీ EMI",
    totalInterest: "మొత్తం వడ్డీ",
    totalPayable: "మొత్తం చెల్లించవలసింది",
    govtSchemes: "ప్రభుత్వ పథకాలు",
    negotiate: "వడ్డీ చర్చ",
  },
  bn: {
    welcome: "FinAI-তে স্বাগতম",
    welcomeSubtitle: "আপনার AI আর্থিক সহায়ক",
    checkLoanRisk: "ঋণ ঝুঁকি পরীক্ষা করুন",
    talkToAI: "AI সহায়কের সাথে কথা বলুন",
    uploadDocuments: "নথি আপলোড করুন",
    financialHealth: "আর্থিক স্বাস্থ্য স্কোর",
    loanRiskForm: "ঋণ ঝুঁকি মূল্যায়ন",
    income: "মাসিক আয়",
    expenses: "মাসিক খরচ",
    existingLoans: "বিদ্যমান ঋণ",
    emi: "��র্তমান EMI",
    calculateRisk: "ঝুঁকি গণনা করুন",
    riskScore: "ঝুঁকি স্কোর",
    lowRisk: "কম ঝুঁকি",
    mediumRisk: "মাঝারি ঝুঁকি",
    highRisk: "উচ্চ ঝুঁকি",
    aiChat: "AI আর্থিক সহায়ক",
    typeMessage: "আপনার বার্তা লিখুন...",
    send: "পাঠান",
    analyzing: "বিশ্লেষণ করা হচ্ছে...",
    extractingData: "ডেটা এক্সট্রাক্ট করা হচ্ছে...",
    financialRoadmap: "আর্থিক রোডম্যাপ",
    repaymentPlan: "পরিশোধের পরিকল্পনা",
    tips: "আর্থিক টিপস",
    creditSimulator: "ক্রেডিট সিমুলেটর",
    documentUpload: "নথি আপলোড",
    uploadPDF: "PDF বা ছবি আপলোড করুন",
    extractedData: "এক্সট্রাক্ট করা ডেটা",
    useForPrediction: "ঝুঁকি পূর্বাভাসের জন্য এই ডেটা ব্যবহার করুন",
    reminders: "অনুস্মারক",
    setReminder: "অনুস্মারক সেট করুন",
    whatsappReminder: "WhatsApp অনুস্মারক",
    confirmReminder: "অনুস্মারক সফলভাবে সেট করা হয়েছে",
    demoMode: "ডেমো মোড",
    selectLanguage: "ভাষা নির্��াচন করুন",
    dashboard: "ড্যাশবোর্ড",
    simulator: "সিমুলেটর",
    roadmap: "রোডম্যাপ",
    chat: "চ্যাট",
    documents: "নথি",
    settings: "সেটিংস",
    loanAmount: "ঋণের পরিমাণ",
    tenure: "মেয়াদ (মাস)",
    loanPurpose: "ঋণের উদ্দেশ্য",
    cibilScore: "CIBIL স্কোর",
    age: "বয়স (বছর)",
    employmentType: "কর্মসংস্থানের ধরন",
    stabilityYears: "বর্তমান চাকরিতে বছর",
    sectionLoanDetails: "আপনি যে ঋণ নিতে চান",
    sectionCreditProfile: "আপনার ক্রেডিট প্রোফাইল",
    bankRateComparison: "ব্যাংক সুদের হার তুলনা",
    yourLoanProfile: "আপনার ঋণ প্রোফাইল",
    compareRates: "সুদের হার তুলনা করুন",
    eligible: "যোগ্য",
    notEligible: "অযোগ্য",
    bestPick: "আপনার জন্য সেরা",
    contactBankBtn: "ব্যাংকে যোগাযোগ করুন",
    sendInquiry: "অনুসন্ধান পাঠান",
    processingFee: "প্রসেসিং ফি",
    goldWeight: "সোনার ওজন (গ্রাম)",
    goldPurity: "সোনার বিশুদ্ধতা (ক্যারেট)",
    eligibleLoanAmt: "যোগ্য ঋণের পরিমাণ",
    calculateLoan: "গণনা করুন",
    viewGoldLoanBanks: "গোল্ড লোন ব্যাংক দেখুন",
    checkMyEligibility: "আমার যোগ্যতা পরীক্ষা করুন",
    compareBanks: "ব্যাংক তুলনা করুন",
    yourLoanJourney: "আপনার ঋণ যাত্রা",
    allFeatures: "সমস্ত বৈশিষ্ট্য",
    generatePlan: "পরিশোধ পরিকল্পনা তৈরি করুন",
    monthlyEmi: "মাসিক EMI",
    totalInterest: "মোট সুদ",
    totalPayable: "মোট প্রদেয়",
    govtSchemes: "সরকারি প্রকল্প",
    negotiate: "সুদের হার আলোচনা",
  },
  mr: {
    welcome: "FinAI मध्ये आपले स्वागत आहे",
    welcomeSubtitle: "तुमचा AI आर्थिक सहाय्यक",
    checkLoanRisk: "कर्ज जोखीम तपासा",
    talkToAI: "AI सहाय्यकाशी बोला",
    uploadDocuments: "कागदपत्रे अपलोड करा",
    financialHealth: "आर्थिक आरोग्य स्कोअर",
    loanRiskForm: "कर्ज जोखीम मूल्यांकन",
    income: "मासिक उत्पन्न",
    expenses: "मासिक खर्च",
    existingLoans: "विद्यमान कर्जे",
    emi: "सध्याची EMI",
    calculateRisk: "जोखीम मोजा",
    riskScore: "जोखीम स्कोअर",
    lowRisk: "कमी जोखीम",
    mediumRisk: "मध्यम जोखीम",
    highRisk: "उच्च जोखीम",
    aiChat: "AI आर्थिक सहाय्यक",
    typeMessage: "तुमचा संदेश टाइप करा...",
    send: "पाठवा",
    analyzing: "विश्लेषण करत आहे...",
    extractingData: "डेटा काढत आहे...",
    financialRoadmap: "आर्थिक रोडमॅप",
    repaymentPlan: "परतफेड योजना",
    tips: "आर्थिक टिप्स",
    creditSimulator: "क्रेडिट सिम्युलेटर",
    documentUpload: "दस्तऐवज अपलोड",
    uploadPDF: "PDF किंवा प्रतिमा अपलोड करा",
    extractedData: "काढलेला डेटा",
    useForPrediction: "जोखीम अंदाजासाठी हा डेटा वापरा",
    reminders: "स्मरणपत्रे",
    setReminder: "स्मरणपत्र सेट करा",
    whatsappReminder: "WhatsApp स्मरणपत्र",
    confirmReminder: "स्मरणपत्र यशस्वीपणे सेट केले",
    demoMode: "डेमो मोड",
    selectLanguage: "भाषा निवडा",
    dashboard: "डॅशबोर्ड",
    simulator: "सिम्युलेटर",
    roadmap: "रोडमॅप",
    chat: "चॅट",
    documents: "कागदपत्रे",
    settings: "सेटिंग्ज",
    loanAmount: "कर्जाची रक्कम",
    tenure: "कालावधी (महिने)",
    loanPurpose: "कर्जाचा उद्देश",
    cibilScore: "CIBIL स्कोअर",
    age: "वय (वर्षे)",
    employmentType: "रोजगाराचा प्रकार",
    stabilityYears: "सध्याच्या नोकरीतील वर्षे",
    sectionLoanDetails: "तुम्हाला घ्यायचे कर्ज",
    sectionCreditProfile: "तुमची क्रेडिट प्रोफाइल",
    bankRateComparison: "बँक व्याजदर तुलना",
    yourLoanProfile: "तुमची कर्ज माहिती",
    compareRates: "दर तुलना करा",
    eligible: "पात्र",
    notEligible: "अपात्र",
    bestPick: "तुमच्यासाठी सर्वोत्तम",
    contactBankBtn: "बँकेशी संपर्क करा",
    sendInquiry: "चौकशी पाठवा",
    processingFee: "प्रक्रिया शुल्क",
    goldWeight: "सोन्याचे वजन (ग्रॅम)",
    goldPurity: "सोन्याची शुद्धता (कॅरेट)",
    eligibleLoanAmt: "पात्र कर्ज रक्कम",
    calculateLoan: "मोजा",
    viewGoldLoanBanks: "गोल्ड लोन बँका पहा",
    checkMyEligibility: "माझी पात्रता तपासा",
    compareBanks: "बँका तुलना करा",
    yourLoanJourney: "तुमचा कर्ज प्रवास",
    allFeatures: "सर्व वैशिष्ट्ये",
    generatePlan: "परतफेड योजना तयार करा",
    monthlyEmi: "मासिक EMI",
    totalInterest: "एकूण व्याज",
    totalPayable: "एकूण देय",
    govtSchemes: "सरकारी योजना",
    negotiate: "व्याजदर वाटाघाटी",
  },
  gu: {
    welcome: "FinAI માં આપનું સ્વાગત છે",
    welcomeSubtitle: "તમારા AI નાણાકીય સહાયક",
    checkLoanRisk: "લોન જોખમ તપાસો",
    talkToAI: "AI સહાયક સાથે વાત કરો",
    uploadDocuments: "દસ્તાવેજો અપલોડ કરો",
    financialHealth: "નાણાકીય સ્વાસ્થ્ય સ્કોર",
    loanRiskForm: "લોન જોખમ મૂલ્યાંકન",
    income: "માસિક આવક",
    expenses: "માસિક ખર્ચ",
    existingLoans: "હાલની લોન",
    emi: "વર્તમાન EMI",
    calculateRisk: "જોખમની ગણતરી કરો",
    riskScore: "જોખમ સ્કોર",
    lowRisk: "ઓછું જોખમ",
    mediumRisk: "મધ્યમ જોખમ",
    highRisk: "ઉચ્ચ જોખમ",
    aiChat: "AI નાણાકીય સહાયક",
    typeMessage: "તમારો સંદેશ લખો...",
    send: "મોકલો",
    analyzing: "વિશ્લેષણ કરી રહ્યા છીએ...",
    extractingData: "ડેટા કાઢી રહ્યા છીએ...",
    financialRoadmap: "નાણાકીય રોડમેપ",
    repaymentPlan: "ચુકવણી યોજના",
    tips: "નાણાકીય ટિપ્સ",
    creditSimulator: "ક્રેડિટ સિમ્યુલેટર",
    documentUpload: "દસ્તાવેજ અપલોડ",
    uploadPDF: "PDF અથવા છબી અપલોડ કરો",
    extractedData: "કાઢેલો ડેટા",
    useForPrediction: "જોખમ અનુમાન માટે આ ડેટાનો ઉપયોગ કરો",
    reminders: "રીમાઇન્ડર્સ",
    setReminder: "રીમાઇન્ડર સેટ કરો",
    whatsappReminder: "WhatsApp રીમાઇન્ડર",
    confirmReminder: "રીમાઇન્ડર સફળતાપૂર્વક સેટ થયું",
    demoMode: "ડેમો મોડ",
    selectLanguage: "ભાષા પસંદ કરો",
    dashboard: "ડેશબોર્ડ",
    simulator: "સિમ્યુલેટર",
    roadmap: "રોડમેપ",
    chat: "ચેટ",
    documents: "દસ્તાવેજો",
    settings: "સેટિંગ્સ",
    loanAmount: "લોનની રકમ",
    tenure: "સમયગાળો (મહિના)",
    loanPurpose: "લોનનો હેતુ",
    cibilScore: "CIBIL સ્કોર",
    age: "ઉંમર (વર્ષ)",
    employmentType: "રોજગારનો પ્રકાર",
    stabilityYears: "વર્તમાન નોકરીમાં વર્ષ",
    sectionLoanDetails: "તમે જે લોન લેવા માંગો છો",
    sectionCreditProfile: "તમારી ક્રેડિટ પ્રોફાઇલ",
    bankRateComparison: "બેંક દર તુલના",
    yourLoanProfile: "તમારી લોન વિગત",
    compareRates: "દરો સરખાવો",
    eligible: "પાત્ર",
    notEligible: "અપાત્ર",
    bestPick: "તમારા માટે શ્રેષ્ઠ",
    contactBankBtn: "બેંકનો સંપર્ક કરો",
    sendInquiry: "પૂછપરછ મોકલો",
    processingFee: "પ્રોસેસિંગ ફી",
    goldWeight: "સોનાનો ભાર (ગ્રામ)",
    goldPurity: "સોનાની શુદ્ધતા (કેરેટ)",
    eligibleLoanAmt: "પાત્ર લોન રકમ",
    calculateLoan: "ગણો",
    viewGoldLoanBanks: "ગોલ્ડ લોન બેંકો જુઓ",
    checkMyEligibility: "મારી પાત્રતા તપાસો",
    compareBanks: "બેંકો સરખાવો",
    yourLoanJourney: "તમારી લોન સફર",
    allFeatures: "બધી સુવિધાઓ",
    generatePlan: "ચૂકવણી યોજના બનાવો",
    monthlyEmi: "માસિક EMI",
    totalInterest: "કુલ વ્યાજ",
    totalPayable: "કુલ ચૂકવવાપાત્ર",
    govtSchemes: "સરકારી યોજનાઓ",
    negotiate: "વ્યાજ વાટાઘાટ",
  },
  ur: {
    welcome: "FinAI میں خوش آمدید",
    welcomeSubtitle: "آپ کا AI مالی معاون",
    checkLoanRisk: "قرض کا خطرہ چیک کریں",
    talkToAI: "AI معاون سے بات کریں",
    uploadDocuments: "دستاویزات اپ لوڈ کریں",
    financialHealth: "مالی صحت اسکور",
    loanRiskForm: "قرض خطرے کی تشخیص",
    income: "ماہانہ آمدنی",
    expenses: "ماہانہ اخراجات",
    existingLoans: "موجودہ قرضے",
    emi: "موجودہ EMI",
    calculateRisk: "خطرے کا حساب لگائیں",
    riskScore: "خطرے کا اسکور",
    lowRisk: "کم خطرہ",
    mediumRisk: "درمیانی خطرہ",
    highRisk: "زیادہ خطرہ",
    aiChat: "AI مالی معاون",
    typeMessage: "اپنا پیغام لکھیں...",
    send: "بھیجیں",
    analyzing: "تجزیہ ہو رہا ہے...",
    extractingData: "ڈیٹا نکالا جا رہا ہے...",
    financialRoadmap: "مالی روڈ میپ",
    repaymentPlan: "ادائیگی کا منصوبہ",
    tips: "مالی مشورے",
    creditSimulator: "کریڈٹ سمیلیٹر",
    documentUpload: "دستاویز اپ لوڈ",
    uploadPDF: "PDF یا تصویر اپ لوڈ کریں",
    extractedData: "نکالا گیا ڈیٹا",
    useForPrediction: "خطرے کی پیشگوئی کے لیے یہ ڈیٹا استعمال کریں",
    reminders: "یاد دہانیاں",
    setReminder: "یاد دہانی سیٹ کریں",
    whatsappReminder: "WhatsApp یاد دہانی",
    confirmReminder: "یاد دہانی کامیابی سے سیٹ ہو گئی",
    demoMode: "ڈیمو موڈ",
    selectLanguage: "زبان منتخب کریں",
    dashboard: "ڈیش بورڈ",
    simulator: "سمیلیٹر",
    roadmap: "روڈ میپ",
    chat: "چیٹ",
    documents: "دستاویزات",
    settings: "ترتیبات",
    loanAmount: "قرض کی رقم",
    tenure: "مدت (ماہ)",
    loanPurpose: "قرض کا مقصد",
    cibilScore: "CIBIL اسکور",
    age: "عمر (سال)",
    employmentType: "ملازمت کی قسم",
    stabilityYears: "موجودہ ملازمت میں سال",
    sectionLoanDetails: "آپ جو قرض لینا چاہتے ہیں",
    sectionCreditProfile: "آپ کا کریڈٹ پروفائل",
    bankRateComparison: "بینک شرح سود کا موازنہ",
    yourLoanProfile: "آپ کا قرض پروفائل",
    compareRates: "شرح سود موازنہ کریں",
    eligible: "اہل",
    notEligible: "نااہل",
    bestPick: "آپ کے لیے بہترین",
    contactBankBtn: "بینک سے رابطہ کریں",
    sendInquiry: "استفسار بھیجیں",
    processingFee: "پروسیسنگ فیس",
    goldWeight: "سونے کا وزن (گرام)",
    goldPurity: "سونے کی خالصیت (قیراط)",
    eligibleLoanAmt: "اہل قرض کی رقم",
    calculateLoan: "حساب لگائیں",
    viewGoldLoanBanks: "گولڈ لون بینک دیکھیں",
    checkMyEligibility: "میری اہلیت جانچیں",
    compareBanks: "بینکوں کا موازنہ کریں",
    yourLoanJourney: "آپ کا قرض سفر",
    allFeatures: "تمام سہولیات",
    generatePlan: "ادائیگی منصوبہ بنائیں",
    monthlyEmi: "ماہانہ EMI",
    totalInterest: "کل سود",
    totalPayable: "کل ادائیگی",
    govtSchemes: "سرکاری اسکیمیں",
    negotiate: "شرح سود مذاکرات",
  },
  pa: {
    welcome: "FinAI ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
    welcomeSubtitle: "ਤੁਹਾਡਾ AI ਵਿੱਤੀ ਸਹਾਇਕ",
    checkLoanRisk: "ਕਰਜ਼ੇ ਦਾ ਜੋਖਮ ਚੈੱਕ ਕਰੋ",
    talkToAI: "AI ਸਹਾਇਕ ਨਾਲ ਗੱਲ ਕਰੋ",
    uploadDocuments: "ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਕਰੋ",
    financialHealth: "ਵਿੱਤੀ ਸਿਹਤ ਸਕੋਰ",
    loanRiskForm: "ਕਰਜ਼ਾ ਜੋਖਮ ਮੁਲਾਂਕਣ",
    income: "ਮਹੀਨਾਵਾਰ ਆਮਦਨ",
    expenses: "ਮਹੀਨਾਵਾਰ ਖਰਚੇ",
    existingLoans: "ਮੌਜੂਦਾ ਕਰਜ਼ੇ",
    emi: "ਮੌਜੂਦਾ EMI",
    calculateRisk: "ਜੋਖਮ ਦੀ ਗਣਨਾ ਕਰੋ",
    riskScore: "ਜੋਖਮ ਸਕੋਰ",
    lowRisk: "ਘੱਟ ਜੋਖਮ",
    mediumRisk: "ਦਰਮਿਆਨਾ ਜੋਖਮ",
    highRisk: "ਉੱਚ ਜੋਖਮ",
    aiChat: "AI ਵਿੱਤੀ ਸਹਾਇਕ",
    typeMessage: "ਆਪਣਾ ਸੁਨੇਹਾ ਲਿਖੋ...",
    send: "ਭੇਜੋ",
    analyzing: "ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    extractingData: "ਡਾਟਾ ਕੱਢਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
    financialRoadmap: "ਵਿੱਤੀ ਰੋਡਮੈਪ",
    repaymentPlan: "ਭੁਗਤਾਨ ਯੋਜਨਾ",
    tips: "ਵਿੱਤੀ ਸੁਝਾਅ",
    creditSimulator: "ਕ੍ਰੈਡਿਟ ਸਿਮੂਲੇਟਰ",
    documentUpload: "ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ",
    uploadPDF: "PDF ਜਾਂ ਤਸਵੀਰ ਅਪਲੋਡ ਕਰੋ",
    extractedData: "ਕੱਢਿਆ ਗਿਆ ਡਾਟਾ",
    useForPrediction: "ਜੋਖਮ ਭਵਿੱਖਬਾਣੀ ਲਈ ਇਹ ਡਾਟਾ ਵਰਤੋ",
    reminders: "ਯਾਦ-ਦਹਾਨੀਆਂ",
    setReminder: "ਯਾਦ-ਦਹਾਨੀ ਸੈੱਟ ਕਰੋ",
    whatsappReminder: "WhatsApp ਯਾਦ-ਦਹਾਨੀ",
    confirmReminder: "ਯਾਦ-ਦਹਾਨੀ ਸਫਲਤਾਪੂਰਵਕ ਸੈੱਟ ਹੋ ਗਈ",
    demoMode: "ਡੈਮੋ ਮੋਡ",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    simulator: "ਸਿਮੂਲੇਟਰ",
    roadmap: "ਰੋਡਮੈਪ",
    chat: "ਚੈਟ",
    documents: "ਦਸਤਾਵੇਜ਼",
    settings: "ਸੈਟਿੰਗਾਂ",
    loanAmount: "ਕਰਜ਼ੇ ਦੀ ਰਕਮ",
    tenure: "ਅਵਧੀ (ਮਹੀਨੇ)",
    loanPurpose: "ਕਰਜ਼ੇ ਦਾ ਉਦੇਸ਼",
    cibilScore: "CIBIL ਸਕੋਰ",
    age: "ਉਮਰ (ਸਾਲ)",
    employmentType: "ਰੁਜ਼ਗਾਰ ਦੀ ਕਿਸਮ",
    stabilityYears: "ਮੌਜੂਦਾ ਨੌਕਰੀ ਵਿੱਚ ਸਾਲ",
    sectionLoanDetails: "ਤੁਸੀਂ ਜੋ ਕਰਜ਼ਾ ਲੈਣਾ ਚਾਹੁੰਦੇ ਹੋ",
    sectionCreditProfile: "ਤੁਹਾਡੀ ਕ੍ਰੈਡਿਟ ਪ੍ਰੋਫਾਈਲ",
    bankRateComparison: "ਬੈਂਕ ਦਰ ਤੁਲਨਾ",
    yourLoanProfile: "ਤੁਹਾਡੀ ਕਰਜ਼ੇ ਦੀ ਜਾਣਕਾਰੀ",
    compareRates: "ਦਰਾਂ ਦੀ ਤੁਲਨਾ ਕਰੋ",
    eligible: "ਯੋਗ",
    notEligible: "ਅਯੋਗ",
    bestPick: "ਤੁਹਾਡੇ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ",
    contactBankBtn: "ਬੈਂਕ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
    sendInquiry: "ਪੁੱਛਗਿੱਛ ਭੇਜੋ",
    processingFee: "ਪ੍ਰੋਸੈਸਿੰਗ ਫੀਸ",
    goldWeight: "ਸੋਨੇ ਦਾ ਭਾਰ (ਗ੍ਰਾਮ)",
    goldPurity: "ਸੋਨੇ ਦੀ ਸ਼ੁੱਧਤਾ (ਕੈਰੇਟ)",
    eligibleLoanAmt: "ਯੋਗ ਕਰਜ਼ੇ ਦੀ ਰਕਮ",
    calculateLoan: "ਗਣਨਾ ਕਰੋ",
    viewGoldLoanBanks: "ਗੋਲਡ ਲੋਨ ਬੈਂਕ ਦੇਖੋ",
    checkMyEligibility: "ਮੇਰੀ ਯੋਗਤਾ ਜਾਂਚੋ",
    compareBanks: "ਬੈਂਕਾਂ ਦੀ ਤੁਲਨਾ ਕਰੋ",
    yourLoanJourney: "ਤੁਹਾਡੀ ਕਰਜ਼ੇ ਦੀ ਯਾਤਰਾ",
    allFeatures: "ਸਾਰੀਆਂ ਸੁਵਿਧਾਵਾਂ",
    generatePlan: "ਭੁਗਤਾਨ ਯੋਜਨਾ ਬਣਾਓ",
    monthlyEmi: "ਮਹੀਨਾਵਾਰ EMI",
    totalInterest: "ਕੁੱਲ ਵਿਆਜ",
    totalPayable: "ਕੁੱਲ ਅਦਾਇਗੀ",
    govtSchemes: "ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ",
    negotiate: "ਵਿਆਜ ਦਰ ਗੱਲਬਾਤ",
  },
  ks: {
    welcome: "FinAI مَنٛز خوش آمدید",
    welcomeSubtitle: "تُہنٛد AI مالی مَددگار",
    checkLoanRisk: "قرض خطرہ چیک کَرِو",
    talkToAI: "AI مَددگار سِتٕ گَژھِو",
    uploadDocuments: "دستاویز اَپلوڈ کَرِو",
    financialHealth: "مالی صحت سکور",
    loanRiskForm: "قرض خطرٕ تشخیص",
    income: "ماہانہ آمدنی",
    expenses: "ماہانہ خرچ",
    existingLoans: "موجودہ قرضہٕ",
    emi: "موجودہ EMI",
    calculateRisk: "خطرٕ حساب لَگاوِو",
    riskScore: "خطرٕ سکور",
    lowRisk: "کَم خطرہ",
    mediumRisk: "درمیانہ خطرہ",
    highRisk: "زیادٕ خطرہ",
    aiChat: "AI مالی مَددگار",
    typeMessage: "پَنُن پیغام لِکھِو...",
    send: "بیاوِو",
    analyzing: "تجزیہ کَران چُھ...",
    extractingData: "ڈیٹا کَڈان چُھ...",
    financialRoadmap: "مالی روڈ میپ",
    repaymentPlan: "ادائیگی منصوبہ",
    tips: "مالی مشورے",
    creditSimulator: "کریڈٹ سِمیلیٹر",
    documentUpload: "دستاویز اَپلوڈ",
    uploadPDF: "PDF یا تصویر اَپلوڈ کَرِو",
    extractedData: "کَڈمُت ڈیٹا",
    useForPrediction: "خطرٕ پیشگوئی بَپَتھ یِہ ڈیٹا استعمال کَرِو",
    reminders: "یاد دہانی",
    setReminder: "یاد دہانی سیٹ کَرِو",
    whatsappReminder: "WhatsApp یاد دہانی",
    confirmReminder: "یاد دہانی کامیاب طور سیٹ گَیہ",
    demoMode: "ڈیمو موڈ",
    selectLanguage: "زبان چُنِو",
    dashboard: "ڈیش بورڈ",
    simulator: "سِمیلیٹر",
    roadmap: "روڈ میپ",
    chat: "چیٹ",
    documents: "دستاویزات",
    settings: "ترتیبات",
    loanAmount: "قرضٕ رقم",
    tenure: "مدت (ماہ)",
    loanPurpose: "قرضٕ مقصد",
    cibilScore: "CIBIL سکور",
    age: "عمر (سال)",
    employmentType: "نوکری قسم",
    stabilityYears: "ہالہ نوکری میں سال",
    sectionLoanDetails: "قرضٕ جو لیو ہیو تُم",
    sectionCreditProfile: "تُہنٛد کریڈٹ پروفائل",
    bankRateComparison: "بینک ریٹ موازنہ",
    yourLoanProfile: "تُہنٛد قرضٕ پروفائل",
    compareRates: "ریٹ موازنہ کَرِو",
    eligible: "اہل",
    notEligible: "نا اہل",
    bestPick: "تُہنٛد بدلہ بہترین",
    contactBankBtn: "بینک سیتی رابطہ کَرِو",
    sendInquiry: "پوچھتاچھ بیاوِو",
    processingFee: "پروسیسنگ فیس",
    goldWeight: "سون وزن (گرام)",
    goldPurity: "سون شُدھتا (قیراط)",
    eligibleLoanAmt: "اہل قرضٕ رقم",
    calculateLoan: "حساب لَگاوِو",
    viewGoldLoanBanks: "گولڈ لوون بینک یِتھ",
    checkMyEligibility: "مے اہلیت چیک کَرِو",
    compareBanks: "بینک موازنہ کَرِو",
    yourLoanJourney: "تُہنٛد قرضٕ سفر",
    allFeatures: "سُوے فیچر",
    generatePlan: "ادائیگی منصوبہ بنَاوِو",
    monthlyEmi: "ماہانہ EMI",
    totalInterest: "کُل سود",
    totalPayable: "کُل ادائیگی",
    govtSchemes: "سرکاری اسکیمیں",
    negotiate: "سود گفتگو",
  },
  as: {
    welcome: "FinAI লৈ আপোনাক স্বাগতম",
    welcomeSubtitle: "আপোনাৰ AI বিত্তীয় সহায়ক",
    checkLoanRisk: "ঋণৰ বিপদ পৰীক্ষা কৰক",
    talkToAI: "AI সহায়কৰ সৈতে কথা পাতক",
    uploadDocuments: "নথিপত্ৰ আপলোড কৰক",
    financialHealth: "বিত্তীয় স্বাস্থ্য স্কোৰ",
    loanRiskForm: "ঋণ বিপদ মূল্যায়ন",
    income: "মাহিলী আয়",
    expenses: "মাহিলী খৰচ",
    existingLoans: "বিদ্যমান ঋণ",
    emi: "বৰ্তমান EMI",
    calculateRisk: "বিপদ গণনা কৰক",
    riskScore: "বিপদ স্কোৰ",
    lowRisk: "কম বিপদ",
    mediumRisk: "মধ্যম বিপদ",
    highRisk: "উচ্চ বিপদ",
    aiChat: "AI বিত্তীয় সহায়ক",
    typeMessage: "আপোনাৰ বাৰ্তা লিখক...",
    send: "পঠাওক",
    analyzing: "বিশ্লেষণ কৰি আছে...",
    extractingData: "তথ্য উলিয়াই আছে...",
    financialRoadmap: "বিত্তীয় ৰোডমেপ",
    repaymentPlan: "পৰিশোধ পৰিকল্পনা",
    tips: "বিত্তীয় পৰামৰ্শ",
    creditSimulator: "ক্ৰেডিট ছিমুলেটৰ",
    documentUpload: "নথিপত্ৰ আপলোড",
    uploadPDF: "PDF বা ছবি আপলোড কৰক",
    extractedData: "উলিওৱা তথ্য",
    useForPrediction: "বিপদ অনুমানৰ বাবে এই তথ্য ব্যৱহাৰ কৰক",
    reminders: "সোঁৱৰণী",
    setReminder: "সোঁৱৰণী ছেট কৰক",
    whatsappReminder: "WhatsApp সোঁৱৰণী",
    confirmReminder: "সোঁৱৰণী সফলতাৰে ছেট হল",
    demoMode: "ডেমো মোড",
    selectLanguage: "ভাষা নিৰ্বাচন কৰক",
    dashboard: "ডেশ্বৰ্ড",
    simulator: "ছিমুলেটৰ",
    roadmap: "ৰোডমেপ",
    chat: "চাট",
    documents: "নথিপত্ৰ",
    settings: "ছেটিংছ",
    loanAmount: "ঋণৰ পৰিমাণ",
    tenure: "মেয়াদ (মাহ)",
    loanPurpose: "ঋণৰ উদ্দেশ্য",
    cibilScore: "CIBIL স্কোৰ",
    age: "বয়স (বছৰ)",
    employmentType: "কৰ্মসংস্থানৰ প্ৰকাৰ",
    stabilityYears: "বৰ্তমান চাকৰিত বছৰ",
    sectionLoanDetails: "আপুনি ল'ব বিচৰা ঋণ",
    sectionCreditProfile: "আপোনাৰ ক্ৰেডিট প্ৰফাইল",
    bankRateComparison: "বেংক সুদৰ হাৰ তুলনা",
    yourLoanProfile: "আপোনাৰ ঋণৰ বিৱৰণ",
    compareRates: "হাৰ তুলনা কৰক",
    eligible: "যোগ্য",
    notEligible: "অযোগ্য",
    bestPick: "আপোনাৰ বাবে সৰ্বোত্তম",
    contactBankBtn: "বেংকৰ সৈতে যোগাযোগ কৰক",
    sendInquiry: "অনুসন্ধান পঠাওক",
    processingFee: "প্ৰচেছিং মাচুল",
    goldWeight: "সোণৰ ওজন (গ্ৰাম)",
    goldPurity: "সোণৰ বিশুদ্ধতা (ক্যাৰেট)",
    eligibleLoanAmt: "যোগ্য ঋণৰ পৰিমাণ",
    calculateLoan: "গণনা কৰক",
    viewGoldLoanBanks: "গোল্ড লোন বেংক চাওক",
    checkMyEligibility: "মোৰ যোগ্যতা পৰীক্ষা কৰক",
    compareBanks: "বেংক তুলনা কৰক",
    yourLoanJourney: "আপোনাৰ ঋণৰ যাত্ৰা",
    allFeatures: "সকলো সুবিধা",
    generatePlan: "পৰিশোধ পৰিকল্পনা তৈয়াৰ কৰক",
    monthlyEmi: "মাহেকীয়া EMI",
    totalInterest: "মুঠ সুদ",
    totalPayable: "মুঠ পৰিশোধযোগ্য",
    govtSchemes: "চৰকাৰী আঁচনি",
    negotiate: "সুদৰ হাৰ আলোচনা",
  },
  mni: {
    welcome: "FinAI দা ওকচরি",
    welcomeSubtitle: "নখোয়গী AI শেন-শুমফম তৌবিগী",
    checkLoanRisk: "মারুপ লেপ্পা য়েংবিয়ু",
    talkToAI: "AI তৌবিগীগা ৱারি শাননু",
    uploadDocuments: "দোক্যুমেন্ত থাদোক্কনু",
    financialHealth: "শেন-শুমফম ফগৎপ স্কোর",
    loanRiskForm: "মারুপ লেপ্পা চেকসিন্নবা",
    income: "থা অমগী লেপ্পা",
    expenses: "থা অমগী শুমফম",
    existingLoans: "লৈরবা মারুপসিং",
    emi: "হৌজিক্কী EMI",
    calculateRisk: "লেপ্পা চেকসিন্নবা",
    riskScore: "লেপ্পা স্কোর",
    lowRisk: "লেপ্পা চংই",
    mediumRisk: "লৈবাক্কী লেপ্পা",
    highRisk: "লেপ্পা য়াম্লবা",
    aiChat: "AI শেন-শুমফম তৌবিগী",
    typeMessage: "নখোয়গী ৱারি থিজিল্লু...",
    send: "থাদোক্কু",
    analyzing: "চেকসিন্নরি...",
    extractingData: "দেতা লৌথোক্তুনা...",
    financialRoadmap: "শেন-শুমফম লম্বি মপা",
    repaymentPlan: "হন্না পিসিনবা মায়োং",
    tips: "শেন-শুমফম য়ানিংঙুম্বা",
    creditSimulator: "ক্রেদিত সিম্যুলেটর",
    documentUpload: "দোক্যুমেন্ত থাদোক্কবা",
    uploadPDF: "PDF নত্রগা মচি থাদোক্কু",
    extractedData: "লৌথোক্তুবা দেতা",
    useForPrediction: "লেপ্পা ইনাক্কবদা মসি দেতা সিজিন্নু",
    reminders: "নিংশিংবীসিং",
    setReminder: "নিংশিংবী থম্মু",
    whatsappReminder: "WhatsApp নিংশিংবী",
    confirmReminder: "নিংশিংবী মফত্তগা থম্লে",
    demoMode: "দেমো মোদ",
    selectLanguage: "ৱা খন্ননু",
    dashboard: "দেশ্বোর্দ",
    simulator: "সিম্যুলেটর",
    roadmap: "লম্বি মপা",
    chat: "ৱারি",
    documents: "দোক্যুমেন্তসিং",
    settings: "সেত্তিংসিং",
    loanAmount: "মারুপ লেপ্পা",
    tenure: "তাইপু (থা)",
    loanPurpose: "মারুপ লেপ্পা লৌবগী কারণ",
    cibilScore: "CIBIL স্কোর",
    age: "চহী (পাউ)",
    employmentType: "থৌদাং লৌবগী মতং",
    stabilityYears: "হৌজিক্কী থৌদাংদা চহী",
    sectionLoanDetails: "নখোয় লৌনিংবা মারুপ",
    sectionCreditProfile: "নখোয়গী ক্রেদিত প্রোফাইল",
    bankRateComparison: "বেংক রেত তুলনা",
    yourLoanProfile: "নখোয়গী মারুপ প্রোফাইল",
    compareRates: "রেত তুলনা তৌবিয়ু",
    eligible: "য়োক্ননিংবা",
    notEligible: "য়োক্নংদবা",
    bestPick: "নখোয়দা ফবা",
    contactBankBtn: "বেংক মাংখিবিয়ু",
    sendInquiry: "খোংজেল থাদোক্কু",
    processingFee: "প্রোসেসিং ফি",
    goldWeight: "সোরারোম শাত্না (গ্রাম)",
    goldPurity: "সোরারোমগী শুদ্ধতা (কেরেত)",
    eligibleLoanAmt: "য়োক্ননিংবা মারুপ লেপ্পা",
    calculateLoan: "চেকসিন্নবিয়ু",
    viewGoldLoanBanks: "গোল্ড লোন বেংক য়েংবিয়ু",
    checkMyEligibility: "এগী য়োক্নংবা চেকসিন্নবিয়ু",
    compareBanks: "বেংকসিং তুলনা তৌবিয়ু",
    yourLoanJourney: "নখোয়গী মারুপ লম্বি",
    allFeatures: "মরম ফেচর",
    generatePlan: "হন্না পিসিনবা মায়োং থাবিয়ু",
    monthlyEmi: "থা অমগী EMI",
    totalInterest: "মতম মরম সুদ",
    totalPayable: "মতম মরম হন্না পিসিনবা",
    govtSchemes: "সরকারী স্কিম",
    negotiate: "সুদ হার আলোচনা",
  },
  or: {
    welcome: "FinAI କୁ ସ୍ୱାଗତ",
    welcomeSubtitle: "ଆପଣଙ୍କର AI ଆର୍ଥିକ ସହାୟକ",
    checkLoanRisk: "ଋଣ ବିପଦ ଯାଞ୍ଚ କରନ୍ତୁ",
    talkToAI: "AI ସହାୟକଙ୍କ ସହ କଥା ହୁଅନ୍ତୁ",
    uploadDocuments: "ଡକ୍ୟୁମେଣ୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ",
    financialHealth: "ଆର୍ଥିକ ସ୍ୱାସ୍ଥ୍ୟ ସ୍କୋର",
    loanRiskForm: "ଋଣ ବିପଦ ମୂଲ୍ୟାଙ୍କନ",
    income: "ମାସିକ ଆୟ",
    expenses: "ମାସିକ ଖର୍ଚ୍ଚ",
    existingLoans: "ବିଦ୍ୟମାନ ଋଣ",
    emi: "ବର୍ତ୍ତମାନର EMI",
    calculateRisk: "ବିପଦ ଗଣନା କରନ୍ତୁ",
    riskScore: "ବିପଦ ସ୍କୋର",
    lowRisk: "କମ୍ ବିପଦ",
    mediumRisk: "ମଧ୍ୟମ ବିପଦ",
    highRisk: "ଉଚ୍ଚ ବିପଦ",
    aiChat: "AI ଆର୍ଥିକ ସହାୟକ",
    typeMessage: "ଆପଣଙ୍କ ସନ୍ଦେଶ ଲେଖନ୍ତୁ...",
    send: "ପଠାନ୍ତୁ",
    analyzing: "ବିଶ୍ଲେଷଣ ହେଉଛି...",
    extractingData: "ତଥ୍ୟ ବାହାର କରୁଛି...",
    financialRoadmap: "ଆର୍ଥିକ ରୋଡମ୍ୟାପ୍",
    repaymentPlan: "ପରିଶୋଧ ଯୋଜନା",
    tips: "ଆର୍ଥିକ ଟିପ୍ସ",
    creditSimulator: "କ୍ରେଡିଟ୍ ସିମୁଲେଟର",
    documentUpload: "ଡକ୍ୟୁମେଣ୍ଟ ଅପଲୋଡ୍",
    uploadPDF: "PDF କିମ୍ବା ଛବି ଅପଲୋଡ୍ କରନ୍ତୁ",
    extractedData: "ବାହାରିଥିବା ତଥ୍ୟ",
    useForPrediction: "ବିପଦ ଭବିଷ୍ୟବାଣୀ ପାଇଁ ଏହି ତଥ୍ୟ ବ୍ୟବହାର କରନ୍ତୁ",
    reminders: "ସ୍ମାରକ",
    setReminder: "ସ୍ମାରକ ସେଟ୍ କରନ୍ତୁ",
    whatsappReminder: "WhatsApp ସ୍ମାରକ",
    confirmReminder: "ସ୍ମାରକ ସଫଳତାର ସହ ସେଟ୍ ହୋଇଛି",
    demoMode: "ଡେମୋ ମୋଡ୍",
    selectLanguage: "ଭାଷା ଚୟନ କରନ୍ତୁ",
    dashboard: "ଡ୍ୟାସବୋର୍ଡ",
    simulator: "ସିମୁଲେଟର",
    roadmap: "ରୋଡମ୍ୟାପ୍",
    chat: "ଚାଟ୍",
    documents: "ଡକ୍ୟୁମେଣ୍ଟ",
    settings: "ସେଟିଂସ",
    loanAmount: "ଋଣ ପରିମାଣ",
    tenure: "ଅବଧି (ମାସ)",
    loanPurpose: "ଋଣ ଉଦ୍ଦେଶ୍ୟ",
    cibilScore: "CIBIL ସ୍କୋର",
    age: "ବୟସ (ବର୍ଷ)",
    employmentType: "ଚାକିରି ପ୍ରକାର",
    stabilityYears: "ବର୍ତ୍ତମାନ ଚାକିରିରେ ବର୍ଷ",
    sectionLoanDetails: "ଆପଣ ଯେ ଋଣ ନେବାକୁ ଚାହୁଁଛନ୍ତି",
    sectionCreditProfile: "ଆପଣଙ୍କ କ୍ରେଡ଼ିଟ୍ ପ୍ରୋଫାଇଲ",
    bankRateComparison: "ବ୍ୟାଙ୍କ ଦର ତୁଳନା",
    yourLoanProfile: "ଆପଣଙ୍କ ଋଣ ବିବରଣ",
    compareRates: "ଦର ତୁଳନା କରନ୍ତୁ",
    eligible: "ଯୋଗ୍ୟ",
    notEligible: "ଅଯୋଗ୍ୟ",
    bestPick: "ଆପଣଙ୍କ ପାଇଁ ସର୍ବୋତ୍ତମ",
    contactBankBtn: "ବ୍ୟାଙ୍କ ସଂଯୋଗ କରନ୍ତୁ",
    sendInquiry: "ଅନୁସନ୍ଧାନ ପଠାନ୍ତୁ",
    processingFee: "ପ୍ରୋସେସିଂ ଶୁଳ୍କ",
    goldWeight: "ସୁନା ଓଜନ (ଗ୍ରାମ)",
    goldPurity: "ସୁନା ବିଶୁଦ୍ଧତା (କ୍ୟାରେଟ)",
    eligibleLoanAmt: "ଯୋଗ୍ୟ ଋଣ ପରିମାଣ",
    calculateLoan: "ଗଣନା କରନ୍ତୁ",
    viewGoldLoanBanks: "ଗୋଲ୍ଡ ଲୋନ ବ୍ୟାଙ୍କ ଦେଖନ୍ତୁ",
    checkMyEligibility: "ମୋ ଯୋଗ୍ୟତା ଯାଞ୍ଚ କରନ୍ତୁ",
    compareBanks: "ବ୍ୟାଙ୍କ ତୁଳନା କରନ୍ତୁ",
    yourLoanJourney: "ଆପଣଙ୍କ ଋଣ ଯାତ୍ରା",
    allFeatures: "ସମସ୍ତ ସୁବିଧା",
    generatePlan: "ପରିଶୋଧ ଯୋଜନା ପ୍ରସ୍ତୁତ କରନ୍ତୁ",
    monthlyEmi: "ମାସିକ EMI",
    totalInterest: "ମୋଟ ସୁଦ",
    totalPayable: "ମୋଟ ଦେୟ",
    govtSchemes: "ସରକାରୀ ଯୋଜନା",
    negotiate: "ସୁଧ ହାର ଆଲୋଚନା",
  },
  kok: {
    welcome: "FinAI क स्वागत",
    welcomeSubtitle: "तुमचो AI आर्थिक सहाय्यक",
    checkLoanRisk: "रीण धोको तपासात",
    talkToAI: "AI सहाय्यक कडेन उलयात",
    uploadDocuments: "दस्तऐवज अपलोड करात",
    financialHealth: "आर्थिक भलायकी स्कोर",
    loanRiskForm: "रीण धोको मूल्यांकन",
    income: "म्हयन्याची जोड",
    expenses: "म्हयन्याचो खर्च",
    existingLoans: "आसपावपी रिणां",
    emi: "आतांची EMI",
    calculateRisk: "धोको मेजून काडात",
    riskScore: "धोको स्कोर",
    lowRisk: "उणो धोको",
    mediumRisk: "मध्यम धोको",
    highRisk: "चड धोको",
    aiChat: "AI आर्थिक सहाय्यक",
    typeMessage: "तुमचो संदेश बरयात...",
    send: "धाडात",
    analyzing: "विश्लेषण चालू आसा...",
    extractingData: "डेटा काडटा...",
    financialRoadmap: "आर्थिक रोडमॅप",
    repaymentPlan: "परतफेड येवजण",
    tips: "आर्थिक टिप्स",
    creditSimulator: "क्रेडिट सिम्युलेटर",
    documentUpload: "दस्तऐवज अपलोड",
    uploadPDF: "PDF वा फोटो अपलोड करात",
    extractedData: "काडिल्लो डेटा",
    useForPrediction: "धोको अदमास खातीर हो डेटा वापरात",
    reminders: "याद करपी",
    setReminder: "याद करपी सेट करात",
    whatsappReminder: "WhatsApp याद करपी",
    confirmReminder: "याद करपी येसस्वीपणान सेट जाली",
    demoMode: "डेमो मोड",
    selectLanguage: "भास निवडात",
    dashboard: "डॅशबोर्ड",
    simulator: "सिम्युलेटर",
    roadmap: "रोडमॅप",
    chat: "चॅट",
    documents: "दस्तऐवज",
    settings: "सेटिंग्ज",
    loanAmount: "रीण रक्कम",
    tenure: "काळावधी (म्हयने)",
    loanPurpose: "रीण उद्देश",
    cibilScore: "CIBIL स्कोर",
    age: "वर्सां (उमर)",
    employmentType: "नोकरी प्रकार",
    stabilityYears: "हाल्या नोकरींत वर्सां",
    sectionLoanDetails: "तुमकां घेवपाचें रीण",
    sectionCreditProfile: "तुमची क्रेडिट प्रोफाइल",
    bankRateComparison: "बँक व्याजदर तुलना",
    yourLoanProfile: "तुमची रीण माहिती",
    compareRates: "दर तुलना करात",
    eligible: "पात्र",
    notEligible: "अपात्र",
    bestPick: "तुमच्यासाठी सर्वोत्तम",
    contactBankBtn: "बँकेशी संपर्क करात",
    sendInquiry: "चौकशी धाडात",
    processingFee: "प्रक्रिया शुल्क",
    goldWeight: "सोन्याचें वजन (ग्राम)",
    goldPurity: "सोन्याची शुद्धता (कॅरेट)",
    eligibleLoanAmt: "पात्र रीण रक्कम",
    calculateLoan: "मेजून काडात",
    viewGoldLoanBanks: "गोल्ड लोन बँका पळयात",
    checkMyEligibility: "माझी पात्रता तपासात",
    compareBanks: "बँका तुलना करात",
    yourLoanJourney: "तुमचो रीण प्रवास",
    allFeatures: "सगळ्यो सुविधा",
    generatePlan: "परतफेड येवजण तयार करात",
    monthlyEmi: "म्हयन्याची EMI",
    totalInterest: "एकूण व्याज",
    totalPayable: "एकूण देय",
    govtSchemes: "सरकारी योजना",
    negotiate: "व्याजदर वाटाघाटी",
  },
}

const languageNames: Record<Language, string> = {
  en: "English",
  hi: "हिंदी",
  ta: "தமிழ்",
  te: "తెలుగు",
  ml: "മലയാളം",
  bn: "বাংলা",
  mr: "मराठी",
  gu: "ગુજરાતી",
  ur: "اردو",
  pa: "ਪੰਜਾਬੀ",
  ks: "कॉशुर",
  as: "অসমীয়া",
  mni: "মৈতৈলোন্",
  or: "ଓଡ଼ିଆ",
  kok: "कोंकणी",
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")
  // Stores auto-translated overrides for keys missing in the target language
  const [autoTranslated, setAutoTranslated] = useState<Record<string, string>>({})

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("finai-language") as Language
    if (savedLanguage && Object.keys(languageNames).includes(savedLanguage)) {
      setLanguageState(savedLanguage)
      import("@/lib/auto-translate").then(m => m.notifyLanguageChange(savedLanguage))
    }
  }, [])

  // When language changes, bulk-translate all English keys missing in target language
  useEffect(() => {
    if (language === "en") { setAutoTranslated({}); return }
    const en = translations["en"]
    const target = translations[language] || {}
    const missingKeys = Object.keys(en).filter(k => !target[k])
    if (missingKeys.length === 0) return

    const cacheKey = `finedge_tkeys_${language}`
    try {
      const cached = JSON.parse(localStorage.getItem(cacheKey) || "{}")
      const stillMissing = missingKeys.filter(k => !cached[k])
      if (Object.keys(cached).length > 0) setAutoTranslated(prev => ({ ...prev, ...cached }))
      if (stillMissing.length === 0) return

      fetch("/api/translate/batch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ texts: stillMissing.map(k => en[k]), target_language: language }),
      })
        .then(r => r.json())
        .then(data => {
          const newEntries: Record<string, string> = {}
          stillMissing.forEach((k, i) => { newEntries[k] = data.translations?.[i] || en[k] })
          const merged = { ...cached, ...newEntries }
          localStorage.setItem(cacheKey, JSON.stringify(merged))
          setAutoTranslated(prev => ({ ...prev, ...merged }))
        })
        .catch(() => {})
    } catch {}
  }, [language])

  // Save language to localStorage when it changes
  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("finai-language", lang)
    import("@/lib/auto-translate").then(m => m.notifyLanguageChange(lang))
  }

  const t = (key: string): string => {
    return translations[language]?.[key]
      || autoTranslated[key]
      || translations["en"][key]
      || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export { languageNames }
